// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using data_protection_common;

#nullable disable

namespace data_protection_common.SqlMigrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("data_protection_common.Entities.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("DataSources");

                    b.HasDiscriminator<string>("SourceType").HasValue("DataSource");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("data_protection_common.Entities.AzureBlobDataSource", b =>
                {
                    b.HasBaseType("data_protection_common.Entities.DataSource");

                    b.Property<string>("BlobName")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("BlobPrefix")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasDiscriminator().HasValue("AzureBlob");
                });

            modelBuilder.Entity("data_protection_common.Entities.DatabaseDataSource", b =>
                {
                    b.HasBaseType("data_protection_common.Entities.DataSource");

                    b.Property<int?>("CommandTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabaseType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Query")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Schema")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.ToTable("DataSources", t =>
                        {
                            t.Property("ConnectionString")
                                .HasColumnName("DatabaseDataSource_ConnectionString");
                        });

                    b.HasDiscriminator().HasValue("Database");
                });

            modelBuilder.Entity("data_protection_common.Entities.FileDataSource", b =>
                {
                    b.HasBaseType("data_protection_common.Entities.DataSource");

                    b.Property<string>("Delimiter")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Encoding")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HasHeader")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("File");
                });

            modelBuilder.Entity("data_protection_common.Entities.FtpDataSource", b =>
                {
                    b.HasBaseType("data_protection_common.Entities.DataSource");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("PrivateKeyPath")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemotePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("UsePassiveMode")
                        .HasColumnType("bit");

                    b.Property<bool>("UseSftp")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasDiscriminator().HasValue("Ftp");
                });

            modelBuilder.Entity("data_protection_common.Entities.S3DataSource", b =>
                {
                    b.HasBaseType("data_protection_common.Entities.DataSource");

                    b.Property<string>("AccessKey")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ObjectKey")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Prefix")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecretKey")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasDiscriminator().HasValue("S3");
                });

            modelBuilder.Entity("data_protection_common.Entities.UrlDataSource", b =>
                {
                    b.HasBaseType("data_protection_common.Entities.DataSource");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("AuthType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BearerToken")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Password")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.ToTable("DataSources", t =>
                        {
                            t.Property("Password")
                                .HasColumnName("UrlDataSource_Password");

                            t.Property("Username")
                                .HasColumnName("UrlDataSource_Username");
                        });

                    b.HasDiscriminator().HasValue("Url");
                });
#pragma warning restore 612, 618
        }
    }
}
